/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Arrow: typeof import('./../src/components/Arrow/index.vue')['default']
    CustomHeader: typeof import('./../src/components/CustomHeader/index.vue')['default']
    CustomModal: typeof import('./../src/components/CustomModal/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
